spring:
  application:
    name: PostMate
  datasource:
    url: jdbc:mysql://192.168.0.20:3306/postmate?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: dnfl4585
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate  # 운영 권장(자동 생성/수정 방지). 개발시엔 update 사용 가능
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    # 네이밍 전략을 표준으로: @Table/@Column에 쓴 이름을 그대로 사용

  thymeleaf:
    enabled: true
    cache: false